### ISSUE TITLE
Response Fetch 

### ISSUE THREAD

**Issue by liangliang** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#1]
The fetch function in Response, $filter should be changed to $filters.

public static function fetch($survey_id, $filters = null, $options = null) {
        if ($survey_id < 1) {
            throw new SurveyGizmoException(500, "Missing survey ID");
        }
        $response = self::_fetch(array('id' => '', 'survey_id' => $survey_id), $filter, $options);
        return $response;
    }

**Comment by SurveyGizmoOfficial** [comment]
Thanks.  We've pushed a fix for this issue.
