### ISSUE TITLE
SurveyGizmo api integration

### ISSUE THREAD

**Issue by vincent1892** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#10]
Hi,

I'm trying to integrate this library to my internal system but I've kind of hit a brick wall. Is there like a function to use in adding survey questions after creating a new survey?

regards,
Vincent

**Comment by SurveyGizmoOfficial** [comment]
Hi Vincent,

Thanks for reaching out! We have added additional sample code to give you an idea of the flow to add survey questions after creating a new survey.

Please update your checkout of the repository, and then navigate into the Samples folder. You will need to copy the example credentials file and supply your own API credentials to run it:

```bash
$ cd ./Samples/
$ cp .credentials.example .credentials
$ vi .credentials
```

We added "new_survey.php" to give you a better idea of how to leverage the library:

[Samples/new_survey.php](https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/blob/master/Samples/new_survey.php)

Let us know if you have any further questions!
- SurveyGizmo Development Team

**Comment by vincent1892** [comment]
Thank you guys highly appreciated!!
