### ISSUE TITLE
Ordering of items in survey response

### ISSUE THREAD

**Issue by muhamed-didovic** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#13]
Hi,

Besides filter option, is there like 'sort' or 'order' option, which I can use in GET request for survey responses (https://restapi.surveygizmo.com/v5/survey/xxxxxx/surveyresponse).

Basically I would sort or order items by date_submitted, right now they are ordered by ID?

**Comment by SurveyGizmoOfficial** [comment]
Hi @muhamed-didovic,

Unfortunately, there are no sorting options for responses from the current API implementation, however, you can filter by the date_submitted if you need to get recently submitted results.

You can learn more at https://apihelp.surveygizmo.com/help/surveyresponse-sub-object-v5#filtering

Best,
SurveyGizmo Team
