### ISSUE TITLE
Creating new export

### ISSUE THREAD

**Issue by alanpoon** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#14]
There is no api for creating new export and returning its report_id.

**Comment by SurveyGizmoOfficial** [comment]
Hi Alan,

You are correct, access to exports is not available via the current API. We're working on an API reboot and will consider this as part of the new API. In the meantime perhaps our scheduled exports or FTP exports will meet your needs:

https://help.surveygizmo.com/help/share-email-and-schedule-an-export

https://help.surveygizmo.com/help/ftp (edited)

Best,
- SurveyGizmo Team
