### ISSUE TITLE
SurveyResponse with Contactlist

### ISSUE THREAD

**Issue by alanpoon** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#19]
Hi is possible to return SurveyResponse's data or total count with contact info like invite custom field1?

**Comment by SurveyGizmoOfficial** [comment]
@alanpoon Custom field data does not return as part of the response, however, the contact ID does which you can then use on the surveycontact object to pull the custom field data. 

Alternatively, you can use a merge code to store the custom field data in a hidden value field which will then be part of the response.
