### ISSUE TITLE
getResponses function in Survey

### ISSUE THREAD

**Issue by liangliang** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#2]
Cannot pass the $page to getResponses function in Survey and $filter is useless in this function.
public function getResponses($filter = null)
    {
        return $this->getSubObjects("SurveyGizmo\Resources\Survey\Response");
    }

**Comment by SurveyGizmoOfficial** [comment]
Thanks.  We've pushed a fix for this issue.
