### ISSUE TITLE
How can I overwrite host from .com to .eu?

### ISSUE THREAD

**Issue by danyal14** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#20]
How can I overwrite host from .com to .eu?

**Comment by SurveyGizmoOfficial** [comment]
Hi there @danyal14,

We are working on resolving this issue shortly. In the interim, as a workaround, you can edit this line to point to the EU API:

https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/blob/41c2829ac68592f307228d2964b3d6af30899fa9/ApiRequest.php#L29

Best,
- SurveyGizmo Dev Team

**Comment by SurveyGizmoOfficial** [comment]
Hi again, @danyal14!

This issue has been addressed in the latest release: https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/releases/tag/v1.0.3-stable

Please refer to our README for more information: https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api#configuring-requests-for-international-data-centers

Best,
– SurveyGizmo Dev Team
