### ISSUE TITLE
Login/Password Action Add/Update Records

### ISSUE THREAD

**Issue by thecodeguru360** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#21]
Is there any endpoint in API to ADD/Update or Delete the Password records?

Like we can do in survey builder.

![cuestionario sobre mentalidad - builder - build 2018-05-28 23-35-48](https://user-images.githubusercontent.com/15095426/40626138-0f28025e-62d0-11e8-9568-f33c3eb8db07.png)

**Comment by SurveyGizmoOfficial** [comment]
Hi @lahashmi!

Unfortunately there is not an API endpoint to modify password records at this time.

Best,
- SurveyGizmo Development Team
