### ISSUE TITLE
How to post survey answer to surverygizmo server

### ISSUE THREAD

**Issue by girish-ankit** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#23]
Hi,
I have implemented your code to my site, which is developed in PHP. I am able to fetch servery question form using \SurveyGizmo\Resources\Survey::get($survey_id); method, but how do I post user submitted answers to surveygizmo server. Kindly give me some guide line.

Thanks,
Ankit Kumar

**Comment by SurveyGizmoOfficial** [comment]
Hi Ankit!

You can see an example of creating a survey response in our code samples: https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/blob/master/Samples/manipulate_survey.php#L95-L106

For further information, you can refer to our v5 API documentation: https://apihelp.surveygizmo.com/help/surveyresponse-sub-object-v5#createobject

Best,
- SurveyGizmo Team
