### ISSUE TITLE
Updating surveyoption requireother v5 not working

### ISSUE THREAD

**Issue by alanpoon** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#24]
Hi, I am trying to update a surveyoption's requireother = true. 
var texturl = "https://restapi.surveygizmo.com/v5/survey/4162127/surveyquestion/27/surveyoption/10048?"+api_str+"&_method=POST"
var o = {
    'properties[requireother]' : 'True',
    'properties[na]' : 'False'
};
$.post(texturl,   // url
       o, // data to be submit
       function(data, status, jqXHR) {// success callback
        console.log("data",JSON.stringify(data));
                //$('p').append('status: ' + status + ', data: ' + data);
        },"jsonp")
The data fetched back is {"result_ok":true,"data":{"id":10048,"title":{"English":"toto specify"},"value":"2","properties":{"disabled":false,"piping_exclude":"false","show_rules":null,"show_rules_logic_map":":5c80a55dbe3d5,5c80a55dbe489,5c80a55dbe489","na":"False","requireother":"True","other":false}}}

But my surveyoption is still not requireother.
Please kindly help.

**Comment by SurveyGizmoOfficial** [comment]
Hi @alanpoon,

Unfortunately, this isn't the appropriate place to answer this question. The github repository you have opened an issue ticket on is the PHP SurveyGizmo API library, and as such, we are unable to assist you with your Javascript API call question here.

We suggest you contact our support team for help with your question, you can reach them by emailing support@sgizmo.com or visit https://help.surveygizmo.com/help/surveygizmo-support-hours for more help.

Best,
- SurveyGizmo Engineering Team
