### ISSUE TITLE
[ENHANCEMENT] Configurable API Request Timeout Duration

### ISSUE THREAD

**Issue by jaredhabeck** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#25]
**Is your feature request related to a problem? Please describe.**
There is an artificial timeout set within the ApiRequest library within your SDK.

It is hardcoded to timeout after 35 seconds: https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/blob/master/ApiRequest.php#L134

SurveyGizmo's API response times have degraded in the past 6 months to far past 35 seconds, causing the SDK in the end to return a fully "nulled out" response.

**Describe the solution you'd like**
Set the timeout to an option or at least perhaps a static class property to modify.

**Describe alternatives you've considered**
I modified our SDK directly to just set the timeout to unlimited.

**Additional context**
https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/blob/master/ApiRequest.php#L134

**Comment by SurveyGizmoOfficial** [comment]
Hi @jaredhabeck,

We implemented the requested enhancement, it is now available in [v1.0.4-stable](https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/releases/tag/v1.0.4-stable).

We appreciate your feedback, regarding the performance issues you are experiencing, and our engineering team will do our best to address your concerns.

Best,
- SurveyGizmo Engineering Team
