### ISSUE TITLE
[ENHANCEMENT] setting the Metaonly flag

### ISSUE THREAD

**Issue by cartman8648** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#27]
Hi,
I can't find a way to set the flag "metaonly" when requesting a survey.

I think it would be sufficient if you could set the flag with the options parameter in the ApiRequest::call methode.

**Comment by SurveyGizmoOfficial** [comment]
Hi @cartman8648,

Thanks for your suggestion! This enhancement request is now available on the "metaonly_flag" branch: https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/tree/metaonly_flag

Please let us know if this works to your satisfaction and we will look at including it in our next major release.

Best,
- SurveyGizmo Engineering Team

**Comment by cartman8648** [comment]
Hi @SurveyGizmoOfficial 

It works as expected now.

Thank you!
