### ISSUE TITLE
Are there any plans to support composer installs?

### ISSUE THREAD

**Issue by swilla** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#3]

**Comment by SurveyGizmoOfficial** [comment]
I sincerely apologize for the delay in getting back to you! 

Thank you for your feedback. Currently we do not have plans to implement this on our own. We are always taking our customers feedback into account and if we continue to hear requests for composer install we can look further into it. If we add it to our roadmap I will be sure to update you! 

Let us know if you have any other feedback or questions! 

Thank you, 
SurveyGizmo Development Team

**Comment by ryross** [comment]
Would you consider merging a pull request if someone made it work with composer?

**Comment by SurveyGizmoOfficial** [comment]
Ryder,

Thanks for your question.  We’d be happy to review a pull request if you made the API library work with composer.

**Comment by ryross** [comment]
Great. After I forked my own version, I found this: https://github.com/boysfromthefactory/PHP_SurveyGizmo_Api/commit/252fde2c578be4ee65c2def77a7b970832244464

**Comment by wvdongen** [comment]
What's the progress on this? It's easy to add...

**Comment by wvdongen** [comment]
Added a pull request, please merge: https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api/pull/6

**Comment by burnhamrobertp** [comment]
As a matter of chance, I'll very much be in need of this in the immediate future for integrating SurveyGizmo into our existing business process

**Comment by SurveyGizmoOfficial** [comment]
Merged in wvdongen's changes adding composer support! Thank's to them for their work!
