### ISSUE TITLE
Packagist Release?

### ISSUE THREAD

**Issue by zachflower** [SurveyGizmoOfficial/PHP_SurveyGizmo_Api#9]
We currently have a client with an immediate need to integrate with the SurveyGizmo API, but I noticed that this SDK has not yet been published to [Packagist](https://packagist.org/) (although there seems to have been some work on the Composer file).

Is this something planned for the near future?

If not, I would be happy to assist or provide guidance on releasing and managing an official Composer package.

**Comment by spacenate** [comment]
Hi Zach!

I'm not sure if @SurveyGizmoOfficial plans to publish their package to Packagist, but I thought I would chime in with an alternate solution that may help in the meantime.

To manage PHP_SurveyGizmo_Api via Composer (right now, even while not registered in Packagist), add the following to your local `composer.json`:

    {
        "repositories": [
            {
                "type": "git",
                "url": "https://github.com/SurveyGizmoOfficial/PHP_SurveyGizmo_Api"
            }
        ],
        "require": {
            "SurveyGizmoOfficial/PHP_SurveyGizmo_Api": "dev-master"
        }
    }

Once this has been added, you can then `composer install` like you normally would, and the package will be fetched from github for you. It will be available through Composer's standard `autoload.php` file as well, so to use the package once it has been installed, simply include `vendor/autoload.php`, and you are all set.

    <?php

    require 'vendor/autoload.php';

    try {
        $sg = SurveyGizmo\SurveyGizmoAPI::auth($api_key, $api_secret);
    } catch (Exception $e) {
        die("Error Authenticating");
    }

I do think it would be great to see this package published to Packagist though! Good luck

**Comment by zachflower** [comment]
Thanks @spacenate, I had considered that option, but we have a strict policy against using unversioned packages in package managers; `dev-master` is simply too brittle to trust in a production environment.

**Comment by wvdongen** [comment]
@SurveyGizmoOfficial Any updates on this? Packagist listing would be appreciated!

**Comment by SurveyGizmoOfficial** [comment]
Thanks for your suggestion! The package is now available in Packagist:

https://packagist.org/packages/surveygizmo/surveygizmo-api
